### ISSUE TITLE
nk-compare multiple excludes

### ISSUE THREAD

**Issue by davama** [networklore/nelkit#3]
Hello, 
This is a very neat software. Still learning how to use it.
Thank you.

We were wondering if it is possible to do multiple excludes withing a "match" block:

```
rules:
 - match:
     string: '^snmp-server'
     exclude: '^snmp-server community public'
     exclude: '^snmp-server community <redacted>'
```

Currently the above would apply the last exclude which contains the "redacted" line.

Thanks
Dave
